// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dlcedsnzahniwvnobxon.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRsY2Vkc256YWhuaXd2bm9ieG9uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4OTI1ODEsImV4cCI6MjA2MDQ2ODU4MX0.pZ4KbuCPeDG6L1WJYtOjmlwMt0zgWyP_kuQWOB_8oYI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);